# Generated by Django 6.0.6 on 2026-06-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintechhub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fintech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurs', models.CharField(max_length=100)),
                ('narx', models.IntegerField(default=0)),
            ],
        ),
    ]
