# Generated by Django 6.0.6 on 2026-06-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintechhub', '0002_fintech'),
    ]

    operations = [
        migrations.AddField(
            model_name='fintech',
            name='mavjudmi',
            field=models.BooleanField(default=True),
        ),
    ]
